---
- hosts: spines
  become: yes
  roles:
    - spines

  handlers:
    - include: handlers/main.yml
      static: yes

- hosts: leafs
  become: yes
  roles:
    - leafs

  handlers:
    - include: handlers/main.yml
      static: yes

- hosts: exits
  become: yes
  roles:
    - exits

  handlers:
    - include: handlers/main.yml
      static: yes
