---
#######
##
## Based on Cumulus quagga-roh demo
## https://github.com/CumulusNetworks/cldemo-vxlan-roh
##
#######

- name: install vlan kernel modules
  apt:
    name: vlan

- name: add the 8021q module
  modprobe:
    name: 8021q
    state: present

- name: Copy interfaces file
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  register: reboot

- name: Install iproute for Quagga dependency
  apt:
    name: iproute
    update_cache: yes
    state: present
    cache_valid_time: 86400

- name: write sysctl files so quagga works correctly on hosts
  copy:
    src: 99cumulus_defaults
    dest: /etc/sysctl.d/99cumulus_defaults.conf
  notify: reload sysctl files

- name: Copy Cumulus Quagga deb
  copy:
    src: roh-ubuntu1604.tar
    dest: /tmp/quagga.tar

- name: Untar Quagga package
  unarchive:
    src: /tmp/quagga.tar
    dest: /tmp/
    copy: no

- name: Install Quagga
  apt:
    deb: /tmp/ubuntu1604/quagga_0.99.23.1-1+cl3u2_xenial_amd64.deb

- name: Copy Quagga daemons file
  copy:
    src: daemons
    dest: /etc/quagga/
  notify: restart quagga

- name: Copy Quagga conf
  template:
    src: Quagga.conf.j2
    dest: /etc/quagga/Quagga.conf
  notify: restart quagga

- name: Ensure Quagga is Started
  service:
    name: quagga
    state: started

#ipaddr package is required for vxrd service
- name: Install ipaddr
  apt:
    name: python-ipaddr
    state: present

# add cumulus pubkey
- name: add cumulus packaging key
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    id: DFEFCFBC5A1A622FEFCA76497EB364B4A88BBC95

# add cumulus repo
- name: install cumulus repo
  copy:
    src: cumulus.list
    dest: /etc/apt/sources.list.d/cumulus.list
  register: update_cache

# update apt cache
- name: update apt cache
  apt:
    update_cache: yes
  when: update_cache.changed

- name: Install LNV package
  apt:
    name: python-vxfld

- name: configure lnv agent
  template:
    src: vxrd.conf.j2
    dest: /etc/vxrd.conf
  notify: restart vxrd

- meta: flush_handlers

- name: reboot
  shell: "shutdown -r 0 now"
  poll: 0
  when: reboot.changed
