---
- name: Apply Quagga daemons
  copy:
    src: daemons
    dest: /etc/quagga/daemons
  notify: restart quagga

- name: Copy /etc/network/interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  notify: reboot
  ignore_errors: true
